version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8501:8501"
      - "8080:8080"
  
  client1:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
      
  client2:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
