FROM python:3.11-slim

RUN apt-get update && apt-get install -y cmake g++ make

WORKDIR /app
COPY . .

RUN mkdir build && cd build && cmake .. && make parking_server_lib

RUN pip install streamlit

EXPOSE 8501
EXPOSE 8080

CMD ["streamlit", "run", "src/ui/app.py", "--server.address=0.0.0.0"]
